/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Alien
 */
public class CasierInterface extends javax.swing.JFrame {

    /**
     * Creates new form AdminInterface
     */
    public CasierInterface() {
        initComponents();
    }
    
    public CasierInterface(String id, String name, String kantin) {
       initComponents();
       int total;
       jLabel2.setText("");
       
       try {
        connect a = new connect();
        login loginn = new login();
        Connection koneks = a.getConnection();
        String com = "SELECT * FROM transaksi WHERE id_kantin='" + kantin + "'";
        Statement stat = koneks.createStatement();
        ResultSet hasil = stat.executeQuery(com);
        jTable1.setModel(DbUtils.resultSetToTableModel(hasil));
        com = "SELECT * FROM kantin WHERE id='" + kantin + "'";
        hasil = stat.executeQuery(com);
        BigDecimal balance = null;
        while(hasil.next()){
            balance = hasil.getBigDecimal("saldo");
        }
        jLabel3.setText("Rp. "+balance );
        com = "SELECT COUNT(id_kantin) FROM transaksi WHERE id_kantin='" + kantin + "'";
        hasil = stat.executeQuery(com);
        while(hasil.next()){
            jLabel2.setText("" + hasil.getInt("COUNT(id_kantin)"));
        }
        
        
        } catch (SQLException ex){
            System.out.println("Gagal update query!");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPopupMenu2.setMaximumSize(new java.awt.Dimension(100, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(884, 500));
        setMinimumSize(new java.awt.Dimension(884, 500));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 205, 255));
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 40, 330, 30);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 205, 255));
        jLabel2.setText("0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 40, 14, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/header.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 890, 140);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1);
        jTextField1.setBounds(350, 70, 200, 50);

        jTextField2.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("0");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField2);
        jTextField2.setBounds(80, 70, 200, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/Group 20.png"))); // NOI18N
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(80, 10, 500, 100);

        kButton1.setText("Pay");
        kButton1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(0, 205, 255));
        kButton1.setkStartColor(new java.awt.Color(0, 205, 255));
        kGradientPanel1.add(kButton1);
        kButton1.setBounds(730, 60, 110, 45);

        kButton3.setText("Top Up");
        kButton3.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 205, 255));
        kButton3.setkStartColor(new java.awt.Color(0, 205, 255));
        kGradientPanel1.add(kButton3);
        kButton3.setBounds(590, 60, 110, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/Kantin HISTORY transaction.png"))); // NOI18N
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(80, 150, 360, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 190, 760, 210);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(-10, 100, 900, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasierInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
