/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import static java.awt.image.ImageObserver.WIDTH;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Popup;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Alien
 */
public class CasierInterface extends javax.swing.JFrame {
    String id, idCasier, idKantin;
    long biilss;
    /**
     * Creates new form AdminInterface
     */
    public CasierInterface() {
        initComponents();
    }
    
    public CasierInterface(String id, String kantin) {
       initComponents();
       int total;
       jLabel2.setText("");
       this.idCasier = id;
       this.idKantin = kantin;
       try {
        connect a = new connect();
        login loginn = new login();
        Connection koneks = a.getConnection();
        String com = "SELECT * FROM transaksi WHERE id_kantin='" + kantin + "'";
        Statement stat = koneks.createStatement();
        ResultSet hasil = stat.executeQuery(com);
        jTable1.setModel(DbUtils.resultSetToTableModel(hasil));
        com = "SELECT * FROM kantin WHERE id='" + kantin + "'";
        hasil = stat.executeQuery(com);
        BigDecimal balance = null;
        while(hasil.next()){
            balance = hasil.getBigDecimal("saldo");
        }
        jLabel3.setText("Rp. "+balance );
        com = "SELECT COUNT(id_kantin) FROM transaksi WHERE id_kantin='" + kantin + "'";
        hasil = stat.executeQuery(com);
        while(hasil.next()){
            jLabel2.setText("" + hasil.getInt("COUNT(id_kantin)"));
        }
        
        
        } catch (SQLException ex){
            System.out.println("Gagal update query!");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        kButton1 = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        bills = new javax.swing.JTextField();
        cust_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kButton3 = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kButton2 = new keeptoo.KButton();
        Refresh = new keeptoo.KButton();

        jPopupMenu2.setMaximumSize(new java.awt.Dimension(100, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(884, 500));
        setMinimumSize(new java.awt.Dimension(884, 500));
        getContentPane().setLayout(null);

        kButton1.setText("Log Out\n");
        kButton1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton1.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 153, 0));
        kButton1.setkSelectedColor(new java.awt.Color(255, 153, 0));
        kButton1.setkStartColor(new java.awt.Color(0, 205, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(710, 30, 130, 40);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 205, 255));
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 40, 330, 30);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 205, 255));
        jLabel2.setText("0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 40, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/header.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 890, 140);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(null);

        bills.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        bills.setForeground(new java.awt.Color(51, 51, 51));
        bills.setText("0");
        bills.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsActionPerformed(evt);
            }
        });
        kGradientPanel1.add(bills);
        bills.setBounds(350, 70, 200, 50);

        cust_id.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        cust_id.setForeground(new java.awt.Color(51, 51, 51));
        cust_id.setText("0");
        cust_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        cust_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_idActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cust_id);
        cust_id.setBounds(80, 70, 200, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/Group 20.png"))); // NOI18N
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(80, 10, 500, 100);

        kButton3.setText("Top Up");
        kButton3.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(255, 153, 0));
        kButton3.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 153, 0));
        kButton3.setkSelectedColor(new java.awt.Color(255, 153, 0));
        kButton3.setkStartColor(new java.awt.Color(0, 205, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3);
        kButton3.setBounds(590, 60, 110, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/image/Kantin HISTORY transaction.png"))); // NOI18N
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(80, 150, 360, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 190, 760, 200);

        kButton2.setText("Pay");
        kButton2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton2.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 153, 0));
        kButton2.setkSelectedColor(new java.awt.Color(255, 153, 0));
        kButton2.setkStartColor(new java.awt.Color(0, 205, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2);
        kButton2.setBounds(730, 60, 110, 45);

        Refresh.setText("Refresh");
        Refresh.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Refresh.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Refresh.setkEndColor(new java.awt.Color(51, 51, 51));
        Refresh.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        Refresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Refresh.setkHoverStartColor(new java.awt.Color(255, 153, 0));
        Refresh.setkSelectedColor(new java.awt.Color(255, 153, 0));
        Refresh.setkStartColor(new java.awt.Color(51, 51, 51));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Refresh);
        Refresh.setBounds(755, 155, 80, 30);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(-10, 100, 900, 410);

        setSize(new java.awt.Dimension(900, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsActionPerformed

    private void cust_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_idActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
       dispose(); 
       new login().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_kButton1ActionPerformed
    
    public String getDataID(){
        return id;
    }
    
    public long getDataBills(){
        return biilss;
    }
    
    
    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        try {                                         
            // TODO add your handling code here:
            String password = "";
            connect a = new connect();
            Connection koneks = a.getConnection();
            id=cust_id.getText();
            biilss = Integer.parseInt(bills.getText());
            String query = "SELECT pin FROM mahasiswa WHERE nim='" + id +"'";
            Statement stat = koneks.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            while(hasil.next()){
                password = hasil.getString("pin");
            }
            if (password.equals("")){
                JOptionPane.showMessageDialog(null, "Akun ini tidak ada", "Error", WIDTH);
            }
            else{
                ConfirmInterface confirm = new ConfirmInterface(id, biilss, idCasier, idKantin);
            confirm.setVisible(rootPaneCheckingEnabled);
            String com = "SELECT * FROM transaksi WHERE id_kantin='" + idKantin + "'";
                hasil = stat.executeQuery(com);
                jTable1.setModel(DbUtils.resultSetToTableModel(hasil));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CasierInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        id=cust_id.getText();
        biilss = Integer.parseInt(bills.getText());
        Confirms confirm = new Confirms(id, biilss, idCasier, idKantin);
        confirm.setVisible(rootPaneCheckingEnabled);
        
        
    }//GEN-LAST:event_kButton2ActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
       int total;
       jLabel2.setText("");
       
       try {
        connect a = new connect();
        login loginn = new login();
        Connection koneks = a.getConnection();
        String com = "SELECT * FROM transaksi WHERE id_kantin='" + idKantin + "'";
        Statement stat = koneks.createStatement();
        ResultSet hasil = stat.executeQuery(com);
        jTable1.setModel(DbUtils.resultSetToTableModel(hasil));
        com = "SELECT * FROM kantin WHERE id='" + idKantin + "'";
        hasil = stat.executeQuery(com);
        BigDecimal balance = null;
        while(hasil.next()){
            balance = hasil.getBigDecimal("saldo");
        }
        jLabel3.setText("Rp. "+balance );
        com = "SELECT COUNT(id_kantin) FROM transaksi WHERE id_kantin='" + idKantin + "'";
        hasil = stat.executeQuery(com);
        while(hasil.next()){
            jLabel2.setText("" + hasil.getInt("COUNT(id_kantin)"));
        }
        
        
        } catch (SQLException ex){
            System.out.println("Gagal update query!");
        }
    }//GEN-LAST:event_RefreshActionPerformed

    
    void setTable(ResultSet hasil){
        jTable1.setModel(DbUtils.resultSetToTableModel(hasil));
    }
    
    void setBalance(long saldo){
        jLabel3.setText("Rp. " + saldo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasierInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton Refresh;
    private javax.swing.JTextField bills;
    private javax.swing.JTextField cust_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
