/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Alien
 */
public class ChangeData extends javax.swing.JFrame {
    String id, pass, confpass;
    /**
     * Creates new form ChangeData
     */
    public ChangeData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        uName2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        uName4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        uName5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(460, 459));
        setPreferredSize(new java.awt.Dimension(460, 459));
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("CONFIRM NEW PIN");
        jLabel10.setToolTipText("");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(60, 230, 190, 50);

        uName2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        uName2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        uName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uName2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(uName2);
        uName2.setBounds(60, 280, 330, 20);

        jLabel1.setFont(new java.awt.Font("Big John", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CHANGE CUSTOMER DATA");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(70, 40, 300, 46);

        uName4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        uName4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        uName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uName4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(uName4);
        uName4.setBounds(60, 140, 330, 20);

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("NIM");
        jLabel12.setToolTipText("");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(60, 90, 240, 50);

        kButton1.setText("CHANGE");
        kButton1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(255, 153, 0));
        kButton1.setkEndColor(new java.awt.Color(0, 205, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        kButton1.setkSelectedColor(new java.awt.Color(255, 153, 0));
        kButton1.setkStartColor(new java.awt.Color(0, 205, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1);
        kButton1.setBounds(60, 330, 330, 45);

        jLabel2.setFont(new java.awt.Font("Big John", 0, 14)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(410, 10, 11, 20);

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("NEW PIN");
        jLabel13.setToolTipText("");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(60, 160, 240, 50);

        uName5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        uName5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        uName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uName5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(uName5);
        uName5.setBounds(60, 210, 330, 20);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 444, 420);

        setSize(new java.awt.Dimension(460, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uName2ActionPerformed

    private void uName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uName4ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        id = uName4.getText();
        pass = uName5.getText();
        confpass = uName2.getText();
        if(pass.equals(confpass)){
             new ConfirmBirth(id, pass).setVisible(rootPaneCheckingEnabled);
        }
        else JOptionPane.showMessageDialog(null, "Ganti Password Gagal, Silahkan cek Kembali Kesamaan Password", "Gagal", WIDTH);
        
       
        
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void uName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uName5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private keeptoo.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField uName2;
    private javax.swing.JTextField uName4;
    private javax.swing.JTextField uName5;
    // End of variables declaration//GEN-END:variables
}
